---
title: Charlie's Blog
description: Charlemagne Santos lives in San Diego and writes software for Sony
paginate: 5
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
port: 3030